### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jzb** [intel/diagnostics-utility#1]
Is there a license for this project? Ideally there'd be a top-level LICENSE file to make this easy to identify and work with.

**Comment by alexander-khvatov** [comment]
@jzb You can find license file for project by `licensing\LICENSE` path. The project is licensed under BSD 3-Clause License

@tingleby Can you handle this feedback?

**Comment by tingleby** [comment]
Yes. I will copy the license file to the top level.
