### ISSUE TITLE
Incorrect build instructions for Linux.

### ISSUE THREAD

**Issue by stolk** [intel/diagnostics-utility#6]
**-DOS=LINUX** flag is not accepted by cmake

```
CMake Error at CMakeLists.txt:41 (message):
  Operation systems name 'LINUX' is incorrect.  Please use LIN or WIN
```

**Comment by amakarev** [comment]
Failed to reproduce the error. CMakeLists.txt also looks correct. Possible problem with CMake cache

**Comment by amakarev** [comment]
@stolk Does the error reproduce? If yes, can you provide more information?
1. operating system
2. cmake version
3. steps to reproduce the error

**Comment by amakarev** [comment]
closed due to inactivity
